# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import werewolves_pb2 as werewolves__pb2


class WerewolvesGameStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/werewolves.WerewolvesGame/Connect',
                request_serializer=werewolves__pb2.PlayerInfo.SerializeToString,
                response_deserializer=werewolves__pb2.MessageResponse.FromString,
                )
        self.Vote = channel.unary_unary(
                '/werewolves.WerewolvesGame/Vote',
                request_serializer=werewolves__pb2.VoteRequest.SerializeToString,
                response_deserializer=werewolves__pb2.VoteResponse.FromString,
                )
        self.ReceiveMessages = channel.unary_stream(
                '/werewolves.WerewolvesGame/ReceiveMessages',
                request_serializer=werewolves__pb2.PlayerInfo.SerializeToString,
                response_deserializer=werewolves__pb2.MessageResponse.FromString,
                )


class WerewolvesGameServicer(object):
    """The service definition.
    """

    def Connect(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Vote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WerewolvesGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=werewolves__pb2.PlayerInfo.FromString,
                    response_serializer=werewolves__pb2.MessageResponse.SerializeToString,
            ),
            'Vote': grpc.unary_unary_rpc_method_handler(
                    servicer.Vote,
                    request_deserializer=werewolves__pb2.VoteRequest.FromString,
                    response_serializer=werewolves__pb2.VoteResponse.SerializeToString,
            ),
            'ReceiveMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveMessages,
                    request_deserializer=werewolves__pb2.PlayerInfo.FromString,
                    response_serializer=werewolves__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'werewolves.WerewolvesGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WerewolvesGame(object):
    """The service definition.
    """

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/werewolves.WerewolvesGame/Connect',
            werewolves__pb2.PlayerInfo.SerializeToString,
            werewolves__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/werewolves.WerewolvesGame/Vote',
            werewolves__pb2.VoteRequest.SerializeToString,
            werewolves__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/werewolves.WerewolvesGame/ReceiveMessages',
            werewolves__pb2.PlayerInfo.SerializeToString,
            werewolves__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
